### ISSUE TITLE
Check hardware access restrictions

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#10]
Conceptual: Can we control the access to hardware, to give some DFEs into the exclusive control of the Adaptation Layer
Discussion with MAX

**Comment by gregorychrysos** [comment]
We asked Maxeler and they told us that there is not a straightforward way to "lock" the DFEs for a specific user. The solution that we suggest is to keep one of our available Maxeler servers just for the needs of the Qualimaster project.  Is there a problem with that?

**Comment by eichelbe** [comment]
As far as I remember, the discussion started with the fact that your servers are accessible to the world. So conceptually, we could at least assume that the machines in a real installation are only accessible within a certain network to the QM infrastructure, the cluster and the administrators. 

As far as I remember, if one DFE is processing, it cannot be just be assigned to another process except the "owner" is unallocating it, or? Then, In combination with the monitoring interface (#11), the QM infrastructure can at least test before it switches to hardware whether DFEs are available (or decide that one has to be unallocated, allocated and loaded by another task).

**Comment by gregorychrysos** [comment]
Yes, the machine will only be accessible by the QM infrastructure and the administrators. 

Yes, the process has to release the DFE in order to set it free again. As far as the second one, the Qualimaster infrastructure will have to run the monitoring "script"  (#11) , in order to be able to define the number of the free DFEs. As far as the DFE unloading, this issue can be handled by the running server process on the Maxeler machine by setting internally the "unloading signals"(this has to be solved during the switch process). 

So this issue is closed as far as the access restrictions.

**Comment by eichelbe** [comment]
Yes, from my perspective.

Then the upload interface (#24) needs functionality to stop processing ;)

**Comment by gregorychrysos** [comment]
Yes, that's another story! :-) :-) So this is issue is closed...
