### ISSUE TITLE
Hardware upload interface

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/qm-issues#24]
Fork from #11 

interface upload algorithms (changing algorithms at runtime)
Deadline: 1.5 months (mid of July)

**Comment by eichelbe** [comment]
may be combined with #44

**Comment by gregorychrysos** [comment]
We started implementing a generic interface for the hardware-based implementations...In more details, we worked on a common interface for the the Hayashi-Yoshida algorithm and Mutual Information. The problem is that maybe it is going to change again due to the serializing issues that need to be solved...

**Comment by ekateriniioannou** [comment]
Gregory will check this in the next days.....

**Comment by eichelbe** [comment]
is there - moved
